In [2]:
from numpy import *
# Single Dimensional Array
array_data1 = [1.4, 7, 8, 12.3]
array1 = array(array_data1)
print("Array 1 : ",array1)

Array 1 :  [ 1.4  7.   8.  12.3]


In [3]:
# Multi dimensional array 
array_data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
array2 = array(array_data2)
print("Array 2: ", array2)

Array 2:  [[1 2 3 4]
 [5 6 7 8]]


In [4]:
# Check the Dimension of the array 
print("Dimension of array2 is ",array2.ndim)

# Check the Size of Array 
print("Shape of array2 is ",array2.shape)

Dimension of array2 is  2
Shape of array2 is  (2, 4)


In [5]:
# Create and array of zeros 
Zero_Array = zeros((3, 6))
print("Zero Array",Zero_Array)

Zero Array [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
# Check Data Type of Array 
array_data1 = [1,2,3,4]
Array1 = array(array_data1)
print("data type of Array1 is : ",Array1.dtype)

data type of Array1 is :  int32


In [7]:
# Arrays and Scalars
# ELement wise array multiplication 
arr1 = array([[1,2,3],[4,5,6]])
arr2 = arr1*arr1 
print("Original Array ",arr1)
print("Element wise sq of arr1 is : ",arr2)
arr3 = arr1*2
print("Double array element wise", arr3)

Original Array  [[1 2 3]
 [4 5 6]]
Element wise sq of arr1 is :  [[ 1  4  9]
 [16 25 36]]
Double array element wise [[ 2  4  6]
 [ 8 10 12]]


In [8]:
# Indexing and slicing of arrays 
# Define Array of 10 elements 
Arr1 = array(arange(10))
print("Arr1 before manipulation is :", Arr1)


# Choose Index pos 3 to 5 and create a sub array 
# Note the 5th Index position actually does not get selected 
# Note: Only elemenst upto the 5th position get selected 
Sub_Arr1 = Arr1[3:5]
# Display elements of sub array 
print("Sub_Array before change is:", Sub_Arr1)


# Assign a fixed value to sub Array Index Pos 0 
Sub_Arr1[0] = 56
# Display elements of Sub_Arr1
print("Sub Array after change :", Sub_Arr1)



# Display elements of original array 
# Note: change in sub Array caused change in main array 
print("Original Array is",Arr1)



# Assign a element to the entire Sub array 
Sub_Arr1 = 66
# Display Sub Arry 
print("Sub Array after new assign is : ",Sub_Arr1)


# Display main Array 
print("Main Array after new assign is : ", Arr1)


Arr1 before manipulation is : [0 1 2 3 4 5 6 7 8 9]
Sub_Array before change is: [3 4]
Sub Array after change : [56  4]
Original Array is [ 0  1  2 56  4  5  6  7  8  9]
Sub Array after new assign is :  66
Main Array after new assign is :  [ 0  1  2 56  4  5  6  7  8  9]


In [17]:
# Boolean Indexing 
# Create an Array of names 
Arr_Names = array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


# Get Array size
Arrsize = Arr_Names.shape
print(Arrsize)
Len1 = Arrsize[0]
print(Len1)


# Create a  Vector of random numbers of the same length
# Init a  Vector of size = Len1 
Rand_Set = array(arange(Len1))

print("Random Numbers: ", Rand_Set)

# Populate Vector with Random nos from 1 to 10 
for i in range(Len1):
    Rand_Set[i-1] = random.uniform(1,10)
    print(Rand_Set) # Important: Random number gets assigned first at -1 position and then from 0 t0 5
    
# Display Rand Vector
print("Rand Vector",Rand_Set)


# Get Those Index positions for which name = Bob 
# Use the index set to choose a sub set of Random Numbers 
Match_name_rand = Rand_Set[Arr_Names == 'Bob']
print("Matching Sub set of Rand Num is:",Match_name_rand)

(7,)
7
Random Numbers:  [0 1 2 3 4 5 6]
[0 1 2 3 4 5 8]
[6 1 2 3 4 5 8]
[6 7 2 3 4 5 8]
[6 7 7 3 4 5 8]
[6 7 7 4 4 5 8]
[6 7 7 4 7 5 8]
[6 7 7 4 7 7 8]
Rand Vector [6 7 7 4 7 7 8]
Matching Sub set of Rand Num is: [6 4]


In [18]:
# Slicing multi dimensional Arrays 
# define a 3 by 4 array 
Array1 = array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array is ", Array1)
Array_Slice1 = Array1[2,:2]
print("Sliced Array is : ",Array_Slice1)


Original Array is  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array is :  [ 9 10]


In [19]:
# Square Root 
Arr = arange(10)
Sqrt_Arr = sqrt(Arr)
print("Sqrt Root values:", Sqrt_Arr )

Sqrt Root values: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [20]:
# Binary Function example 
# Create Two Arrays of 10 random numbers each 
x = random.randn(10)
y = random.randn(10)
# Print  both the arrays 
print("X Array is :", x)
print("Y Array is :", y)
# Get the Element wise max, comparing both arrays 
Max_XY = maximum(x,y)
print("The Max element wise is :", Max_XY)

X Array is : [ 0.24966614  0.63250033 -1.27648415 -0.09624331  1.01263393  0.76621834
 -0.59884419 -0.18475065 -1.08733268  0.62677776]
Y Array is : [ 1.5236005   0.0134438  -0.39403322 -0.53101665 -1.39773342 -0.06435791
 -0.054242    0.33665157  0.23050571  0.34496952]
The Max element wise is : [ 1.5236005   0.63250033 -0.39403322 -0.09624331  1.01263393  0.76621834
 -0.054242    0.33665157  0.23050571  0.62677776]


In [21]:
 # Conditional logic as Array Operators
# Define Boolean Array 
Bool_Arr = array([True,False,True,False,True])
X_Arr = array([1,2,3,4,5])
Y_Arr = array([10,20,30,40,50])

Choice = [(X if Z else Y) for X,Y,Z in zip(X_Arr,Y_Arr,Bool_Arr)]
print("Choice: ",Choice)

Choice:  [1, 20, 3, 40, 5]


In [22]:
# The where clause in arrays 
# Create a 3x3 array of random numbers 
Arr3 = random.randn(3,3)
print("original  Array is : ", Arr3)
# Replace pos numbers with +2 and _ve nos with -2 
Arr3_Chg = where(Arr3 > 0, 2, -2)
# Print changed Array 
print("Chg Array is : ", Arr3_Chg)

original  Array is :  [[ 0.02935829 -0.56404369 -0.26327927]
 [-0.35371242  0.78706348  0.68390539]
 [ 0.97929571  1.28436503  0.06593395]]
Chg Array is :  [[ 2 -2 -2]
 [-2  2  2]
 [ 2  2  2]]


In [23]:
# Basic Statistical Functions
Arr_Stat = array([[1,2,3],[4,5,6],[7,8,9]])
# Mean
Arr_Mean = mean(Arr_Stat) 
print("Mean of Array is: ", Arr_Mean)

Mean of Array is:  5.0


In [24]:
# Sum 
Arr_Sum = sum(Arr_Stat)
print("Sum of Array is:",Arr_Sum)

Sum of Array is: 45


In [25]:
# Get Column means (0th dimension or axis )
Arr_Mean_Cols = Arr_Stat.mean(0)
print("Col_Means = :", Arr_Mean_Cols)


Col_Means = : [4. 5. 6.]


In [26]:
#   Sorting 
Arr4 = array([10,2,34,5])
Arr4_Sorted = sorted(Arr4) 
print("Unsorted Array is ",Arr4)
print("Sorted Array is ",Arr4_Sorted)

Unsorted Array is  [10  2 34  5]
Sorted Array is  [2, 5, 10, 34]


In [27]:
#  Unique  and other Array set operations 
# Create a Names Array 
Names_Arr = array(["Jim","Bob","Roy","Rajesh","Roy","Kumar","Jeet","Roy","Joy"])
# Get Unique Names 
Names_Arr_Unq = unique(Names_Arr)
print("Unique Names are ", Names_Arr_Unq)

Unique Names are  ['Bob' 'Jeet' 'Jim' 'Joy' 'Kumar' 'Rajesh' 'Roy']


In [28]:
# Generate a 4 by 4  Array of random numbers following 
# Normal distribution 
Arr4by4 = random.normal(size=(4,4))
print(Arr4by4)

[[-2.19059218 -0.63137662  1.08351212  0.50774797]
 [ 1.49064264  0.42160043  0.67414661  1.02056263]
 [-0.9353865   0.1946611   0.24642176  0.58661314]
 [-0.43785167 -0.79087459 -1.34054415  1.16025144]]


In [29]:
array1 = [5,6,7,8] 
array_data = [[1, 2, 3, 4], array1] 
array2 = array_data
print(len(array2))

2


In [31]:
import numpy as np
arr1 = np.array([10,10,10])
arr2 = arr1 + arr1
arr3 = arr2*2
print(arr3)

[40 40 40]


In [32]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a
print (c[2])

21


In [33]:
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print (d[1,2])

5
