In [1]:
# Merging
from pandas import *
from numpy import *
from scipy import *
import re

In [2]:
# Data Set Merging With one or more keys : Def is Inner Join 

df1 = DataFrame({'key': ['a', 'a', 'b', 'b', 'c', 'c', 'd'],
     'data1': range(7)})
print(df1)

df2 = DataFrame({'key': ['a', 'b', 'c','e'],
     'data2': range(4)})

print(df2)

  key  data1
0   a      0
1   a      1
2   b      2
3   b      3
4   c      4
5   c      5
6   d      6
  key  data2
0   a      0
1   b      1
2   c      2
3   e      3


In [3]:
# Many to Many Merge 
merged_df = merge(df1,df2,on='key') 
merged_df

key  data1  data2
0   a      0      0
1   a      1      0
2   b      2      1
3   b      3      1
4   c      4      2
5   c      5      2

In [4]:
# Key Col names are different : def is inner Join 
#-----------------------------------------------------
df3 = DataFrame({'Leftkey': ['a', 'a', 'b', 'b', 'c', 'c', 'd'],
     'data1': range(7)})
print(df3)

# Create DF2
df4 = DataFrame({'Rightkey': ['a', 'b', 'c','e'],
     'data2': range(4)})
print(df4)

merged_dfnew = merge(df3,df4,left_on='Leftkey',right_on ='Rightkey') 

merged_dfnew

  Leftkey  data1
0       a      0
1       a      1
2       b      2
3       b      3
4       c      4
5       c      5
6       d      6
  Rightkey  data2
0        a      0
1        b      1
2        c      2
3        e      3


Leftkey  data1 Rightkey  data2
0       a      0        a      0
1       a      1        a      0
2       b      2        b      1
3       b      3        b      1
4       c      4        c      2
5       c      5        c      2

In [5]:
# Outer Join example 
merged_Outer = merge(df1,df2,how='outer')
merged_Outer

key  data1  data2
0   a    0.0    0.0
1   a    1.0    0.0
2   b    2.0    1.0
3   b    3.0    1.0
4   c    4.0    2.0
5   c    5.0    2.0
6   d    6.0    NaN
7   e    NaN    3.0

In [6]:
#----------------------------------------------------------------------------
# Merge in Index
#--------------------------------------------------------------------------
LeftDF= DataFrame({'key': ['a', 'a', 'b', 'b', 'c', 'd'],
 'value': range(6)})
print(LeftDF)


RightDF = DataFrame({'group_val': [3.5,7]}, index=['a','b'])
print(RightDF)

Merged_Ind = merge(LeftDF,RightDF,left_on='key', right_index=True)
print(Merged_Ind)

  key  value
0   a      0
1   a      1
2   b      2
3   b      3
4   c      4
5   d      5
   group_val
a        3.5
b        7.0
  key  value  group_val
0   a      0        3.5
1   a      1        3.5
2   b      2        7.0
3   b      3        7.0


In [9]:
# Concatenation
# Concat Array side by side with alternate axis 
Arr1 = np.arange(12).reshape((3, 4))
print(Arr1)
Arr_Stack = concatenate([Arr1, Arr1], axis=1)
print(Arr_Stack)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: scipy.concatenate is deprecated and will be removed in SciPy 2.0.0, use numpy.concatenate instead
  """


In [10]:
#  Concat Series : default is Axis = 0 
S1 = Series([0, 1], index=['a', 'b'])
S2 = Series([3, 4], index=['c', 'd'])
S3 = Series([5, 9], index=['e', 'f'])

Merged_Ser = concat([S1, S2, S3])
Merged_Ser 

a    0
b    1
c    3
d    4
e    5
f    9
dtype: int64

In [11]:
#  Concat Series : Axis = 1  Will convert to Dataframe 
Merged_Axis1 = concat([S1, S2, S3], axis=1)
Merged_Axis1

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  3.0  NaN
d  NaN  4.0  NaN
e  NaN  NaN  5.0
f  NaN  NaN  9.0

In [12]:
# Create DF with Duplicates
DupDF = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
print(DupDF)


    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4


In [13]:
# Check if Each row is duplicated row or not 
DupDF.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [14]:
# Remove Duplicate Rows 
NoDup = DupDF.drop_duplicates()
print(NoDup)

    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4


In [15]:
# Create Additional Column 
DupDF['NewCol'] = range(7)
print(DupDF)

# Now Drop duplicates based on values in first col only 
NoDup1 = DupDF.drop_duplicates(['k1'])
print(NoDup1)

    k1  k2  NewCol
0  one   1       0
1  one   1       1
2  one   2       2
3  two   3       3
4  two   3       4
5  two   4       5
6  two   4       6
    k1  k2  NewCol
0  one   1       0
3  two   3       3


In [16]:
#  Replace missing values 
DF1data = Series([1., -999., 2., -999., -1000., 3.])
print(DF1data)

# Replace -999  with NA's 
DF2data = DF1data.replace(-999, np.nan)
print(DF2data)

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64
0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64


In [17]:
# Discretization and Binning
# Create Input Set 
Ser1 = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
# Define bin ranges  
Ser1_bins = [18,25,35,65,100]

# Allocate data to bins 
Ser1_Binned = cut(Ser1,Ser1_bins)

# Check data type : will be categorical 
type(Ser1_Binned)

pandas.core.arrays.categorical.Categorical

In [18]:
print(Ser1_Binned)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 65], (35, 65], (35, 65], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 65] < (65, 100]]


In [19]:
# Generate Frequency table : Type is Series 
Ser1_freq = value_counts(Ser1_Binned)
print(Ser1_freq)
Ser1_ind = Ser1_freq.index
print(Ser1_ind)

(18, 25]     5
(35, 65]     4
(25, 35]     3
(65, 100]    0
dtype: int64
CategoricalIndex([(18, 25], (35, 65], (25, 35], (65, 100]], categories=[(18, 25], (25, 35], (35, 65], (65, 100]], ordered=True, dtype='category')


In [20]:
# Create Data frame with Freq Table Information 
Freq_Table_DF = DataFrame({'Bin':Ser1_freq.index, 'Count':Ser1_freq.values})
Freq_Table_DF

Bin  Count
0   (18, 25]      5
1   (35, 65]      4
2   (25, 35]      3
3  (65, 100]      0

In [21]:
# Change Bin Names to meaningful ones 
bin_names = ['Youth', 'Young Adult', 'Middle Age', 'Senior Citizen']
Ser2_Binned = cut(Ser1,Ser1_bins,labels= bin_names)
Ser2_freq = value_counts(Ser2_Binned)
Ser2_ind = Ser2_freq.index
Freq_Table_DF_Named = DataFrame({'Bin':Ser2_freq.index, 'Count':Ser2_freq.values})
# Display 
Freq_Table_DF_Named 

Bin  Count
0           Youth      5
1      Middle Age      4
2     Young Adult      3
3  Senior Citizen      0

In [22]:
# Outlier handling
# Set Seed
random.seed(123) 
# Create a Dataframe of dimension 4 COlumns having 1000 rows of random values each 
DF1 = DataFrame(random.randn(1000,4))
#DF1

# Capture all rows which  has abs value greater than 3 
DF1_GT3 = DF1[(abs(DF1)>3).any(1)]
DF1_GT3

0         1         2         3
48   0.199582 -0.126118  0.197019 -3.231055
182  0.272735  0.425336 -0.230904  3.571579
235 -3.167055 -0.713989 -1.112364 -1.254184
409  0.151037  0.069403 -3.801378 -1.127172
423  0.231228  1.076113 -3.587494  1.148869
510  0.506533  0.644099 -3.066988 -1.349275
910  3.050755  0.296552 -0.481843  0.930787

In [23]:
# Permutation and Random sampling
#Create a  data Frame -  5 Rows, 4 Columns 
DF1 = DataFrame(arange(5*4).reshape(5,4))
DF1

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: scipy.arange is deprecated and will be removed in SciPy 2.0.0, use numpy.arange instead
  This is separate from the ipykernel package so we can avoid doing imports until


0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [24]:
# Create a Random Permutation of Row Length 
Sequence1 = random.permutation(5)
Sequence1

array([3, 4, 1, 2, 0])

In [26]:
#  Change DataFrame Row Positions per sequence
DF2 = DF1.take(Sequence1)
DF2

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [27]:
# Dummy variable creation
# Create a Column of Categorical Data 
DF1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                 'data1': range(6)})
DF1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [28]:
# Note that the Col <key> has categorical data 
# Now we create dummy columns  for the categorical data 

DummyDF = get_dummies(DF1['key'])
DummyDF

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [29]:
# Quiz
import pandas as pd
Ser1 = pd.Series(np.arange(5),index=['a', 'b', 'c', 'd','e'])
print(Ser1['b'])

1


In [30]:
df3 = DataFrame({'Leftkey': ['b', 'a', 'c', 'a'],
'data1': range(4)})
print(df3)

  Leftkey  data1
0       b      0
1       a      1
2       c      2
3       a      3


In [31]:
df3 = pd.DataFrame({'Leftkey': ['b', 'a', 'c', 'a'], 'data1': range(4)})
df4 = pd.DataFrame({'Rightkey': ['a', 'b', 'd','a'],'data2': range(4)})
merged_dfnew = pd.merge(df3,df4,left_on='Leftkey',right_on ='Rightkey')
print(df3)
print(df4)
print(merged_dfnew)
print((merged_dfnew).shape[0])

  Leftkey  data1
0       b      0
1       a      1
2       c      2
3       a      3
  Rightkey  data2
0        a      0
1        b      1
2        d      2
3        a      3
  Leftkey  data1 Rightkey  data2
0       b      0        b      1
1       a      1        a      0
2       a      1        a      3
3       a      3        a      0
4       a      3        a      3
5


In [32]:
Arr1 = np.arange(9).reshape((3, 3))
Arr_Stack = np.concatenate([Arr1, Arr1], axis=0)  # by row
print(Arr_Stack)
Arr_Stack_col = np.concatenate([Arr1, Arr1], axis=1)  # by col
print(Arr_Stack_col)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


In [33]:
DF1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
DummyDF = pd.get_dummies(DF1['key'])
print(DummyDF)

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0
