In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6], [7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.09271278, 0.86884275, 0.19721561, 0.17808023, 0.21728175])

In [19]:
np.random.rand(5,5)

array([[0.31987891, 0.13686355, 0.14796842, 0.73352334, 0.40519374],
       [0.99301288, 0.53826399, 0.26844324, 0.00104007, 0.43791696],
       [0.62301742, 0.42180859, 0.19444742, 0.81867736, 0.15626091],
       [0.57812045, 0.22900131, 0.60121623, 0.29213895, 0.63766898],
       [0.11282852, 0.05779788, 0.42564087, 0.95555757, 0.0557308 ]])

In [20]:
np.random.randn(2)

array([-0.70503219, -0.02317906])

In [22]:
np.random.randint(1,100,10)

array([56, 73, 54, 77, 66,  5, 21, 11, 74,  6])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr=np.random.randint(0,50,10)

In [26]:
ranarr

array([ 9,  0,  8, 43, 15, 37, 34, 36, 20, 15])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [29]:
ranarr.max()

43

In [30]:
ranarr.min()

0

In [31]:
ranarr.argmax()

3

In [32]:
ranarr.argmin()

1

In [34]:
arr.shape

(25,)

In [35]:
arr=arr.reshape(5,5)

In [36]:
arr.shape

(5, 5)

In [37]:
arr.dtype

dtype('int32')